name : learning
on: [push]
jobs:
    # run-shell-commands:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: echo a string
    #           run: echo "hello world"
    #         - name: Multiline command
    #           run: |
    #             node -v
    #             npm -v
    bake_ci:
        runs-on: windows-latest
        steps:
            - name: get the windows version
              run: winver            
                
