name : learning
on: [push]
jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: |
                echo $GITHUB_SHA
            - name: Copy the code
              uses: actions/checkout@v3
              



            
